import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Left from "./Left";
import Right from "./Right";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-wrap px-5 lg:px-24 justify-between">
          <div className="hidden lg:block lg:w-2/12 w-full relative">
            <div className="sticky top-0 h-screen overflow-hidden">
              <Left />
            </div>
          </div>
          <div className="w-full lg:w-7/12 px-5 lg:px-9 relative overflow-auto">
            {children}
          </div>
          <div className="hidden lg:block lg:w-3/12 w-full relative">
            <div className="sticky top-0 h-screen overflow-hidden">
              <Right />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
